name: Base_TR_Reg

on:
  schedule:
    - cron: '0 * * * 0,6'
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - Run tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Configure playwright
      run: playwright install

    - name: Run tests
      if: >
        github.event_name == 'schedule' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.deployment_target == 'Run tests')
      run: pytest test_init.py -v